---
name: Run javascript linter
    
on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
    
jobs:
  run-lint:
    name: Lint Base Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Run linter in base code
        uses: github/super-linter:slim-v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    